### ISSUE TITLE
Fails to import gist if description has a carriage return in it (\r\n)

### ISSUE THREAD

**Issue by cpswan** [mdp/GistEvernoteImport#8]
Here's the stack trace

```
"Creating cloud-localds from Ubuntu 13.04\r\nplace in /usr/bin on older dists (e.g. 12.04) for https://gist.github.com/6221258"
/var/lib/gems/1.9.1/gems/evernote-thrift-1.25.1/lib/Evernote/EDAM/note_store.rb:684:in `recv_createNote': Evernote::EDAM::Error::EDAMUserException
        from /var/lib/gems/1.9.1/gems/evernote-thrift-1.25.1/lib/Evernote/EDAM/note_store.rb:674:in `createNote'
        from /var/lib/gems/1.9.1/gems/evernote_oauth-0.2.3/lib/evernote_oauth/thrift_client_delegation.rb:11:in `method_missing'
        from /GistEvernoteImport/evernote_gist_store.rb:32:in `import'
        from import.rb:26:in `block in <main>'
        from import.rb:16:in `each'
        from import.rb:16:in `<main>'
```

I've worked around this by editing the gist description for that one, which luckily was the only one of mine affected. I don't even know how I put it there in the first place.

**Comment by mdp** [comment]
I should put this in a separate commit, but it's in the latest master now - https://github.com/mdp/GistEvernoteImport/commit/e4990da7d702ee5ff46fe70fcee465172e90f87d#diff-3648877553acafb503e134ba967eba70L21
